/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/passkeys/authentication/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentication Options */
        post: operations["authentication_options_api_v1_auth_passkeys_authentication_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/authentication/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentication Verify */
        post: operations["authentication_verify_api_v1_auth_passkeys_authentication_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/reauthentication/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthentication Options */
        post: operations["reauthentication_options_api_v1_auth_passkeys_reauthentication_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/reauthentication/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthentication Verify */
        post: operations["reauthentication_verify_api_v1_auth_passkeys_reauthentication_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/registration/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registration Options */
        post: operations["registration_options_api_v1_auth_passkeys_registration_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/registration/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registration Verify */
        post: operations["registration_verify_api_v1_auth_passkeys_registration_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Logout */
        delete: operations["logout_api_v1_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Session */
        post: operations["refresh_session_api_v1_auth_session_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/safety-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Safety Capabilities Diagnostic
         * @description Report static safety boundaries without exposing a product action.
         */
        get: operations["safety_capabilities_diagnostic_api_v1_diagnostics_safety_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version Diagnostic */
        get: operations["version_diagnostic_api_v1_diagnostics_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Formal Report */
        get: operations["formal_report_api_v1_reports__report_version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_version_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report User Facts */
        get: operations["report_user_facts_api_v1_reports__report_version_id__facts_get"];
        put?: never;
        /** Record Report User Fact */
        post: operations["record_report_user_fact_api_v1_reports__report_version_id__facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthenticationVerificationDto
         * @description Pydantic transport contract for a completed passkey authentication.
         */
        AuthenticationVerificationDto: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** CapabilityVersion */
        CapabilityVersion: {
            implementation: components["schemas"]["DecisionCaseVersionBundle"];
            /** Policy Version */
            policy_version: string;
            qualification_policy?: components["schemas"]["QualificationPolicy"] | null;
            /** Version Id */
            version_id: string;
        };
        /** ChallengeDto */
        ChallengeDto: {
            /** Challenge Id */
            challenge_id: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
        };
        /**
         * CorrectionEvidence
         * @description New authoritative synthetic facts, distinct from the original Run's evidence.
         */
        CorrectionEvidence: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "2.0.0";
            /** Corrected Statement */
            corrected_statement: string;
            /** Corrects Evidence Id */
            corrects_evidence_id: string;
            /** Decision Formed At */
            decision_formed_at: string;
            evidence_clock: components["schemas"]["EvidenceClock"];
            /** Evidence Id */
            evidence_id: string;
            /** Knowledge Cutoff */
            knowledge_cutoff: string;
            /** Original Statement */
            original_statement: string;
            /** Reason */
            reason: string;
            /** Source */
            source: string;
        };
        /** CredentialRequest */
        CredentialRequest: {
            /** Challenge Id */
            challenge_id: string;
            /** Credential */
            credential: {
                [key: string]: unknown;
            };
        };
        /**
         * DecisionCaseVersionBundle
         * @description The complete implementation version set that participates in replay.
         */
        DecisionCaseVersionBundle: {
            /** Agent Definition Id */
            agent_definition_id: string;
            /** Agent Definition Version */
            agent_definition_version: string;
            /** Case Contract Version */
            case_contract_version: string;
            /** Host Application Version */
            host_application_version: string;
            /** Host Contract Version */
            host_contract_version: string;
            /** Host Source Sha */
            host_source_sha: string;
            /** M Agent Release Commit */
            m_agent_release_commit: string;
            /** M Agent Version */
            m_agent_version: string;
            /** M Agent Wheel Sha256 */
            m_agent_wheel_sha256: string;
            /** M Agent Wheel Url */
            m_agent_wheel_url: string;
            /** Model Adapter Id */
            model_adapter_id: string;
            /** Output Contract Version */
            output_contract_version: string;
            /** Report Projection Contract Version */
            report_projection_contract_version: string;
            /** Routing Policy Version */
            routing_policy_version: string;
        };
        /** EstablishedObligation */
        EstablishedObligation: {
            /** Basis Reference */
            basis_reference: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "REDUCE" | "EXIT";
            /** Obligation Id */
            obligation_id: string;
            /**
             * Quantity Status
             * @constant
             */
            quantity_status: "UNKNOWN";
        };
        /**
         * EvidenceClock
         * @description The immutable fact, publication, acquisition, and validation clocks.
         */
        EvidenceClock: {
            /** Acquired At */
            acquired_at: string;
            /** Fact Effective At */
            fact_effective_at: string;
            /** Source Published At */
            source_published_at: string;
            /** Validated At */
            validated_at: string;
        };
        /**
         * ExternalResult
         * @description The user-visible result expected from this original synthetic fixture.
         */
        ExternalResult: {
            correction_evidence?: components["schemas"]["CorrectionEvidence"] | null;
            governance?: components["schemas"]["GovernanceOutcome"] | null;
            /** Key Reasons */
            key_reasons: string[];
            /** Outcome Code */
            outcome_code: string;
            /** Summary */
            summary: string;
        };
        /** FormalCheckIdentity */
        FormalCheckIdentity: {
            /** Index */
            index: number;
            /**
             * Planned Nodes
             * @default []
             */
            planned_nodes: string[];
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            /**
             * Required Gates
             * @default []
             */
            required_gates: string[];
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Sequence Id */
            sequence_id: string;
        };
        /**
         * FormalReport
         * @description Read-only delivery projection derived from one committed host event.
         */
        FormalReport: {
            access_scope?: components["schemas"]["ResultAccessScope"] | null;
            /** Business Object Id */
            business_object_id: string;
            /** Case Id */
            case_id: string;
            /** Corrects Event Id */
            corrects_event_id?: string | null;
            /** Event Id */
            event_id: string;
            evidence_clock: components["schemas"]["EvidenceClock"];
            /** Framework Run Id */
            framework_run_id: string;
            /** Generated At */
            generated_at: string;
            /** Knowledge Cutoff */
            knowledge_cutoff: string;
            /** Qualification Scope */
            qualification_scope: string;
            /** Report Version Id */
            report_version_id: string;
            result: components["schemas"]["ExternalResult"];
            /** Stage Results */
            stage_results: components["schemas"]["StageResult"][];
            /** Synthetic */
            synthetic: boolean;
            version_bundle: components["schemas"]["DecisionCaseVersionBundle"];
        };
        /** FrozenTask */
        FrozenTask: {
            /** Activation Id */
            activation_id: string | null;
            /** Decision Id */
            decision_id: string;
            /**
             * Freeze Status
             * @enum {string}
             */
            freeze_status: "APPROVED" | "DENIED";
            /**
             * Frozen At
             * Format: date-time
             */
            frozen_at: string;
            node: components["schemas"]["LegalTaskNode"];
            qualification_snapshot: components["schemas"]["QualificationRecord"] | null;
            /** Reasons */
            reasons: string[];
            scope: components["schemas"]["QualificationScope"];
            version: components["schemas"]["CapabilityVersion"];
        };
        /**
         * GateResult
         * @description One deterministic gate evaluated during a saved decision stage.
         */
        GateResult: {
            /** Gate Id */
            gate_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PASSED" | "FAILED" | "UNKNOWN";
        };
        /** GovernanceOutcome */
        GovernanceOutcome: {
            activation?: components["schemas"]["VersionActivation"] | null;
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "APPROVED" | "DENIED";
            policy_binding?: components["schemas"]["PolicyBinding"] | null;
            qualification?: components["schemas"]["QualificationRecord"] | null;
            /** Reasons */
            reasons: string[];
            task?: components["schemas"]["FrozenTask"] | null;
            task_node?: components["schemas"]["RegisteredTaskNode"] | null;
            usage?: components["schemas"]["TaskUsage"] | null;
        };
        /** LegalTaskNode */
        LegalTaskNode: {
            /**
             * Deterministic Obligations
             * @default []
             */
            deterministic_obligations: components["schemas"]["EstablishedObligation"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "MONTHLY" | "DAILY" | "RENEWAL";
            /**
             * Knowledge Cutoff
             * Format: date-time
             */
            knowledge_cutoff: string;
            /** Node Id */
            node_id: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Task Identity */
            task_identity: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
        };
        /** OpaqueRequestErrorDto */
        OpaqueRequestErrorDto: {
            /**
             * Detail
             * @default request is not permitted
             * @constant
             */
            detail: "request is not permitted";
        };
        /**
         * PolicyBinding
         * @description Frozen scoped policy input, independent of whether authority was obtained.
         */
        PolicyBinding: {
            scope: components["schemas"]["QualificationScope"];
            version: components["schemas"]["CapabilityVersion"];
        };
        /** QualificationEvidence */
        QualificationEvidence: {
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Digest */
            digest: string;
            /**
             * Evaluation End
             * Format: date-time
             */
            evaluation_end: string;
            /** Evidence Id */
            evidence_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            formal_check?: components["schemas"]["FormalCheckIdentity"] | null;
            /**
             * Gate Results
             * @default []
             */
            gate_results: components["schemas"]["QualificationGate"][];
            /** Generator Version */
            generator_version: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "QUALIFICATION_PASS" | "DIAGNOSTIC_ALERT" | "INSUFFICIENT_EVIDENCE" | "REQUIRED_PREMISE_UNVERIFIABLE" | "ORIGINAL_BASIS_INVALID" | "RESTORATION_DECISION" | "ORIGINAL_BASIS_RESTORED" | "REQUALIFICATION_PASS" | "HISTORICAL_OOS_PASS" | "LOCKED_FORWARD_PASS" | "FORMAL_CHECK";
            /** Maturity Sufficient */
            maturity_sufficient?: boolean | null;
            /** Resolves Evidence Id */
            resolves_evidence_id?: string | null;
            /** Restored Authorization Digest */
            restored_authorization_digest?: string | null;
            scope: components["schemas"]["QualificationScope"];
            /** Seed */
            seed: number;
            /** State Activity End */
            state_activity_end?: string | null;
            /**
             * Synthetic
             * @constant
             */
            synthetic: true;
            version: components["schemas"]["CapabilityVersion"];
        };
        /** QualificationGate */
        QualificationGate: {
            /** Gate Id */
            gate_id: string;
            /** Passed */
            passed: boolean;
        };
        /**
         * QualificationPolicy
         * @description Explicit D0 policy input, never a default for personal authorization.
         */
        QualificationPolicy: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1.0.0";
            /** Evaluation Max Age Months */
            evaluation_max_age_months: number;
            /** Generator Version */
            generator_version: string;
            /** Policy Version */
            policy_version: string;
            /** Require State Activity */
            require_state_activity: boolean;
            /** Seed */
            seed: number;
            /** State Activity Max Age Months */
            state_activity_max_age_months: number;
            /**
             * Synthetic
             * @constant
             */
            synthetic: true;
        };
        /** QualificationRecord */
        QualificationRecord: {
            /**
             * Alerts
             * @default []
             */
            alerts: components["schemas"]["QualificationEvidence"][];
            authorization_evidence: components["schemas"]["QualificationEvidence"] | null;
            /** Authorization Id */
            authorization_id: string | null;
            /** Authorization Terminated At */
            authorization_terminated_at?: string | null;
            /** Cause */
            cause: string;
            /** Decision Id */
            decision_id: string;
            evidence: components["schemas"]["QualificationEvidence"];
            formal_evidence?: components["schemas"]["QualificationEvidence"] | null;
            formal_passing_evidence?: components["schemas"]["QualificationEvidence"] | null;
            /** Last Formal Node */
            last_formal_node?: string | null;
            /** Previous Decision Id */
            previous_decision_id?: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            requalification?: components["schemas"]["RequalificationProof"] | null;
            /**
             * Restoration Evidence
             * @default []
             */
            restoration_evidence: components["schemas"]["QualificationEvidence"][];
            /**
             * Restrictions
             * @default []
             */
            restrictions: components["schemas"]["QualificationRestriction"][];
            scope: components["schemas"]["QualificationScope"];
            /**
             * Status
             * @enum {string}
             */
            status: "NOT_OBTAINED" | "VALID" | "AT_RISK" | "SUSPENDED" | "REVOKED";
            version: components["schemas"]["CapabilityVersion"];
        };
        /** QualificationRestriction */
        QualificationRestriction: {
            /**
             * Cause
             * @enum {string}
             */
            cause: "REQUIRED_PREMISE_UNVERIFIABLE" | "ORIGINAL_BASIS_INVALID" | "EVIDENCE_EXPIRED" | "FORMAL_PERFORMANCE_FAILURE";
            evidence: components["schemas"]["QualificationEvidence"];
        };
        /** QualificationScope */
        QualificationScope: {
            /** Account Ids */
            account_ids: string[];
            /** Account Type */
            account_type: string;
            /** Board */
            board: string;
            /** Capability */
            capability: string;
            /**
             * Evidence Level
             * @constant
             */
            evidence_level: "D0";
            /** Holding Age Domain */
            holding_age_domain?: string | null;
            /** Market State */
            market_state: string;
            /** Portfolio Scope */
            portfolio_scope?: string | null;
            /** Probability Grid */
            probability_grid?: string | null;
            /** Purpose */
            purpose: string;
            /** Renewal Ordinal */
            renewal_ordinal?: string | null;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** User Id */
            user_id: string;
        };
        /**
         * ReauthenticationVerificationDto
         * @description Pydantic transport contract for a completed recent reauthentication.
         */
        ReauthenticationVerificationDto: {
            /** Credential Id */
            credential_id: string;
        };
        /** RegisteredTaskNode */
        RegisteredTaskNode: {
            /** Decision Id */
            decision_id: string;
            node: components["schemas"]["LegalTaskNode"];
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            scope: components["schemas"]["QualificationScope"];
        };
        /** RequalificationProof */
        RequalificationProof: {
            /** Application Id */
            application_id: string;
            /**
             * First Prediction Frozen At
             * Format: date-time
             */
            first_prediction_frozen_at: string;
            forward_evidence: components["schemas"]["QualificationEvidence"];
            historical_evidence: components["schemas"]["QualificationEvidence"];
            /**
             * Locked At
             * Format: date-time
             */
            locked_at: string;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
        };
        /**
         * ResultAccessScope
         * @description Immutable ownership and visibility bound before a scoped case is executed.
         */
        ResultAccessScope: {
            /** Account Ids */
            account_ids: string[];
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1.0.0";
            /** User Id */
            user_id: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "USER" | "SHADOW";
        };
        /**
         * SafetyCapabilitiesDiagnosticDto
         * @description Machine-readable official-project safety invariants.
         */
        SafetyCapabilitiesDiagnosticDto: {
            /** Order Writing */
            order_writing: boolean;
            /** Public Recommendation Service */
            public_recommendation_service: boolean;
            /** Single User */
            single_user: boolean;
        };
        /**
         * SessionRefreshDto
         * @description Pydantic transport contract for a CSRF-protected idle-session refresh.
         */
        SessionRefreshDto: {
            /** Status */
            status: string;
        };
        /**
         * StageResult
         * @description A phase-specific outcome; lifecycle states have no global terminal meaning.
         */
        StageResult: {
            /** Gate Results */
            gate_results: components["schemas"]["GateResult"][];
            /**
             * Phase
             * @enum {string}
             */
            phase: "FRAMEWORK_RUN" | "HOST_VALIDATION" | "BUSINESS_DECISION" | "QUALIFICATION" | "ADJUDICATION_LIFECYCLE" | "VALIDITY_LIFECYCLE" | "EXECUTION_LIFECYCLE" | "COMMIT_RECONCILIATION" | "BUSINESS_COMMIT" | "PUBLICATION" | "NOTIFICATION" | "CORRECTION";
            /** Reasons */
            reasons: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "CREATED" | "RUNNING" | "WAITING" | "SUCCEEDED" | "REJECTED" | "ABSTAINED" | "FAILED" | "PENDING" | "EXPIRED" | "EXECUTION_BLOCKED" | "UNKNOWN" | "CANCELLED";
        };
        /** TaskUsage */
        TaskUsage: {
            /** Allowed */
            allowed: boolean;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            qualification_snapshot: components["schemas"]["QualificationRecord"] | null;
            /** Reasons */
            reasons: string[];
            task_snapshot: components["schemas"]["FrozenTask"];
        };
        /** UserFact */
        UserFact: {
            /**
             * Authoritative Execution
             * @default false
             * @constant
             */
            authoritative_execution: false;
            /** Choice */
            choice: ("ACCEPT" | "DECLINE" | "DEFER") | null;
            /** Declaration */
            declaration: string | null;
            /** Event Id */
            event_id: string;
            /** Fact Id */
            fact_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "VIEWED" | "ACKNOWLEDGED" | "CONFIRMED" | "EXECUTION_DECLARED";
            /**
             * Reconciliation Status
             * @enum {string}
             */
            reconciliation_status: "NOT_APPLICABLE" | "PENDING";
            /** Recorded At */
            recorded_at: string;
            /** Report Version Id */
            report_version_id: string;
            /**
             * Synthetic
             * @default true
             * @constant
             */
            synthetic: true;
        };
        /** UserFactRequest */
        UserFactRequest: {
            /** Choice */
            choice?: ("ACCEPT" | "DECLINE" | "DEFER") | null;
            /** Declaration */
            declaration?: ("PREPARING" | "REPORTED_SUBMITTED" | "REPORTED_PARTIAL" | "REPORTED_FILLED" | "REPORTED_CANCELLED" | "UNABLE") | null;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "VIEWED" | "ACKNOWLEDGED" | "CONFIRMED" | "EXECUTION_DECLARED";
        };
        /** VersionActivation */
        VersionActivation: {
            /** Decision Id */
            decision_id: string;
            first_node: components["schemas"]["LegalTaskNode"];
            /** Previous Activation Id */
            previous_activation_id: string | null;
            previous_version: components["schemas"]["CapabilityVersion"] | null;
            qualification_snapshot: components["schemas"]["QualificationRecord"];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Retained Task Ids */
            retained_task_ids: string[];
            scope: components["schemas"]["QualificationScope"];
            version: components["schemas"]["CapabilityVersion"];
        };
        /**
         * VersionDiagnosticDto
         * @description Pydantic-only transport contract for the public diagnostic interface.
         */
        VersionDiagnosticDto: {
            /** Application Version */
            application_version: string;
            /** M Agent Release Commit */
            m_agent_release_commit: string;
            /** M Agent Version */
            m_agent_version: string;
            /** M Agent Wheel Sha256 */
            m_agent_wheel_sha256: string;
            /** M Agent Wheel Url */
            m_agent_wheel_url: string;
            /** Source Sha */
            source_sha: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authentication_options_api_v1_auth_passkeys_authentication_options_post: {
        parameters: {
            query?: never;
            header?: {
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDto"];
                };
            };
            /** @description No enrolled passkey is available */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    authentication_verify_api_v1_auth_passkeys_authentication_verify_post: {
        parameters: {
            query?: never;
            header?: {
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationVerificationDto"];
                };
            };
            /** @description Authentication verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    reauthentication_options_api_v1_auth_passkeys_reauthentication_options_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDto"];
                };
            };
            /** @description Recent authenticated session required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    reauthentication_verify_api_v1_auth_passkeys_reauthentication_verify_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReauthenticationVerificationDto"];
                };
            };
            /** @description Reauthentication verification failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    registration_options_api_v1_auth_passkeys_registration_options_post: {
        parameters: {
            query?: never;
            header: {
                "X-Host-Console-Grant": string;
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDto"];
                };
            };
            /** @description Host console grant required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    registration_verify_api_v1_auth_passkeys_registration_verify_post: {
        parameters: {
            query?: never;
            header?: {
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Registration verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    logout_api_v1_auth_session_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin, CSRF token, or session was invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    refresh_session_api_v1_auth_session_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRefreshDto"];
                };
            };
            /** @description Origin, CSRF token, or session was invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    safety_capabilities_diagnostic_api_v1_diagnostics_safety_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyCapabilitiesDiagnosticDto"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    version_diagnostic_api_v1_diagnostics_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDiagnosticDto"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    formal_report_api_v1_reports__report_version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_version_id: string;
            };
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormalReport"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Formal report not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    report_user_facts_api_v1_reports__report_version_id__facts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_version_id: string;
            };
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFact"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    record_report_user_fact_api_v1_reports__report_version_id__facts_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path: {
                report_version_id: string;
            };
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserFactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFact"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
}
