/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/passkeys/authentication/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentication Options */
        post: operations["authentication_options_api_v1_auth_passkeys_authentication_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/authentication/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentication Verify */
        post: operations["authentication_verify_api_v1_auth_passkeys_authentication_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/reauthentication/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthentication Options */
        post: operations["reauthentication_options_api_v1_auth_passkeys_reauthentication_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/reauthentication/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthentication Verify */
        post: operations["reauthentication_verify_api_v1_auth_passkeys_reauthentication_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/registration/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registration Options */
        post: operations["registration_options_api_v1_auth_passkeys_registration_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/registration/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registration Verify */
        post: operations["registration_verify_api_v1_auth_passkeys_registration_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Logout */
        delete: operations["logout_api_v1_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Session */
        post: operations["refresh_session_api_v1_auth_session_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/safety-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Safety Capabilities Diagnostic
         * @description Report static safety boundaries without exposing a product action.
         */
        get: operations["safety_capabilities_diagnostic_api_v1_diagnostics_safety_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version Diagnostic */
        get: operations["version_diagnostic_api_v1_diagnostics_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Formal Report */
        get: operations["formal_report_api_v1_reports__report_version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_version_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report User Facts */
        get: operations["report_user_facts_api_v1_reports__report_version_id__facts_get"];
        put?: never;
        /** Record Report User Fact */
        post: operations["record_report_user_fact_api_v1_reports__report_version_id__facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountCashState
         * @description Cash decomposition retained with the account that supplied it.
         */
        AccountCashState: {
            /** Account Equity */
            account_equity: string | null;
            account_equity_evidence: components["schemas"]["PositionEvidence"];
            account_evidence: components["schemas"]["PositionEvidence"];
            /** Account Id */
            account_id: string;
            /** Account Type */
            account_type: string;
            cash_state_evidence: components["schemas"]["PositionEvidence"];
            /** Currency */
            currency: string;
            /** Frozen Cash */
            frozen_cash: string | null;
            /** Ledger Cash */
            ledger_cash: string | null;
            /**
             * Ledger Cash Semantics
             * @constant
             */
            ledger_cash_semantics: "OPENING_BALANCE_PLUS_AUTHORITATIVE_LEDGER";
            /** Opening Ledger Cash */
            opening_ledger_cash: string | null;
            opening_ledger_cash_evidence: components["schemas"]["PositionEvidence"];
            /** Payable Cash */
            payable_cash: string | null;
            /** Receivable Cash */
            receivable_cash: string | null;
            /** Trading Cash */
            trading_cash: string | null;
            /** Transferable Cash */
            transferable_cash: string | null;
        };
        /**
         * AccountExecutionRestriction
         * @description An execution restriction projected with the account that supplied it.
         */
        AccountExecutionRestriction: {
            /** Account Id */
            account_id: string;
            /** Active */
            active: boolean;
            evidence: components["schemas"]["PositionEvidence"];
            /** Kind */
            kind: string;
            /** Reason */
            reason: string;
            /** Restriction Id */
            restriction_id: string;
            /** Security Id */
            security_id?: string | null;
        };
        /**
         * AccountOpenOrder
         * @description An unfinished order projected with the account that supplied it.
         */
        AccountOpenOrder: {
            /** Account Id */
            account_id: string;
            evidence: components["schemas"]["PositionEvidence"];
            /** Order Id */
            order_id: string;
            /** Remaining Quantity */
            remaining_quantity: string | null;
            /** Reserved Cash */
            reserved_cash: string | null;
            /**
             * Reserved Cash Semantics
             * @enum {string}
             */
            reserved_cash_semantics: "BROKER_FINAL_RESERVED_CASH" | "NOT_APPLICABLE";
            /** Security Id */
            security_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
        };
        /** AlertClosure */
        AlertClosure: {
            /** Alert Evidence Id */
            alert_evidence_id: string;
            evidence: components["schemas"]["QualificationEvidence"];
            proof: components["schemas"]["AlertClosureProof"];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            recorded_replay?: components["schemas"]["RecordedAlertReplay"] | null;
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "DISAPPEARED" | "PROVEN_ERRONEOUS" | "TRANSFERRED" | "ARCHIVED";
        };
        /** AlertClosureProof */
        AlertClosureProof: {
            /** Alert Evidence Id */
            alert_evidence_id: string;
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1.0.0";
            /** Erroneous Replay Id */
            erroneous_replay_id?: string | null;
            /**
             * Observations
             * @default []
             */
            observations: components["schemas"]["DiagnosticObservation"][];
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "DISAPPEARED" | "PROVEN_ERRONEOUS" | "TRANSFERRED" | "ARCHIVED";
            resolution_evidence?: components["schemas"]["QualificationEvidence"] | null;
            /** Rule Version */
            rule_version: string;
            /** Transferred Restriction Evidence Id */
            transferred_restriction_evidence_id?: string | null;
        };
        /**
         * AuthenticationVerificationDto
         * @description Pydantic transport contract for a completed passkey authentication.
         */
        AuthenticationVerificationDto: {
            /** Csrf Token */
            csrf_token: string;
        };
        /**
         * AuthoritativeLedgerEntry
         * @description An append-only ledger entry projected with its source account identity.
         */
        AuthoritativeLedgerEntry: {
            /** Account Id */
            account_id: string;
            /** Cash Delta */
            cash_delta: string;
            /** Cost Basis Delta */
            cost_basis_delta: string;
            /** Entry Id */
            entry_id: string;
            /**
             * Entry Type
             * @enum {string}
             */
            entry_type: "FILL" | "FEE" | "TRANSFER_IN" | "TRANSFER_OUT" | "CORPORATE_ACTION";
            evidence: components["schemas"]["PositionEvidence"];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Quantity Delta */
            quantity_delta: string;
            /** Security Id */
            security_id: string | null;
        };
        /** BasisSubstitutionCheck */
        BasisSubstitutionCheck: {
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Check Id */
            check_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "EQUIVALENCE" | "MIGRATION" | "CROSS_VALIDATION" | "REPLAY";
            /** Original Basis Digest */
            original_basis_digest: string;
            /**
             * Passed
             * @constant
             */
            passed: true;
            /** Substitute Basis Digest */
            substitute_basis_digest: string;
        };
        /** CapabilityVersion */
        CapabilityVersion: {
            implementation: components["schemas"]["DecisionCaseVersionBundle"];
            /** Policy Version */
            policy_version: string;
            qualification_policy?: components["schemas"]["QualificationPolicy"] | null;
            /** Version Id */
            version_id: string;
        };
        /** CashBudget */
        CashBudget: {
            /** Hard Ratio */
            hard_ratio: string;
            /** Target Ratio */
            target_ratio: string;
        };
        /** CertifiedBasisSubstitution */
        CertifiedBasisSubstitution: {
            /** Checks */
            checks: components["schemas"]["BasisSubstitutionCheck"][];
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1.0.0";
            /** Dependency Windows */
            dependency_windows: components["schemas"]["CertifiedDependencyWindow"][];
            /** Original Basis Digest */
            original_basis_digest: string;
            /** Substitute Basis Digest */
            substitute_basis_digest: string;
        };
        /** CertifiedDependencyWindow */
        CertifiedDependencyWindow: {
            /** Original Dependency Artifact Id */
            original_dependency_artifact_id: string;
            /**
             * Required From
             * Format: date-time
             */
            required_from: string;
            /**
             * Required Until
             * Format: date-time
             */
            required_until: string;
            /** Substitute Dependency Artifact Id */
            substitute_dependency_artifact_id: string;
        };
        /** ChallengeDto */
        ChallengeDto: {
            /** Challenge Id */
            challenge_id: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
        };
        /**
         * CompleteAccountSnapshot
         * @description One whole account at the portfolio cutoff, never a virtual allocation slice.
         */
        CompleteAccountSnapshot: {
            /** Account Id */
            account_id: string;
            /** Account Type */
            account_type: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Cash Fact Id */
            cash_fact_id: string;
            /** Currency */
            currency: string;
            /** Payables Fact Id */
            payables_fact_id: string;
            /** Permissions */
            permissions: string[];
            /** Positions Fact Id */
            positions_fact_id: string;
            /** Receivables Fact Id */
            receivables_fact_id: string;
            /**
             * Scope
             * @constant
             */
            scope: "FULL_ACCOUNT";
            /** Unfinished Trades Fact Id */
            unfinished_trades_fact_id: string;
        };
        /**
         * CorrectionEvidence
         * @description New authoritative synthetic facts, distinct from the original Run's evidence.
         */
        CorrectionEvidence: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "2.0.0";
            /** Corrected Statement */
            corrected_statement: string;
            /** Corrects Evidence Id */
            corrects_evidence_id: string;
            /** Decision Formed At */
            decision_formed_at: string;
            evidence_clock: components["schemas"]["EvidenceClock"];
            /** Evidence Id */
            evidence_id: string;
            /** Knowledge Cutoff */
            knowledge_cutoff: string;
            /** Original Statement */
            original_statement: string;
            /** Reason */
            reason: string;
            /** Source */
            source: string;
        };
        /** CredentialRequest */
        CredentialRequest: {
            /** Challenge Id */
            challenge_id: string;
            /** Credential */
            credential: {
                [key: string]: unknown;
            };
        };
        /**
         * DatedCashObligation
         * @description A forward-recorded cash requirement that the selected portfolio must preserve.
         */
        DatedCashObligation: {
            /** Amount */
            amount: string;
            /**
             * Latest Usable At
             * Format: date-time
             */
            latest_usable_at: string;
            /** Obligation Id */
            obligation_id: string;
            /** Purpose */
            purpose: string;
            /** Target Account Id */
            target_account_id: string;
        };
        /**
         * DecisionCaseVersionBundle
         * @description The complete implementation version set that participates in replay.
         */
        DecisionCaseVersionBundle: {
            /** Agent Definition Id */
            agent_definition_id: string;
            /** Agent Definition Version */
            agent_definition_version: string;
            /** Case Contract Version */
            case_contract_version: string;
            /** Host Application Version */
            host_application_version: string;
            /** Host Contract Version */
            host_contract_version: string;
            /** Host Source Sha */
            host_source_sha: string;
            /** M Agent Release Commit */
            m_agent_release_commit: string;
            /** M Agent Version */
            m_agent_version: string;
            /** M Agent Wheel Sha256 */
            m_agent_wheel_sha256: string;
            /** M Agent Wheel Url */
            m_agent_wheel_url: string;
            /** Model Adapter Id */
            model_adapter_id: string;
            /** Output Contract Version */
            output_contract_version: string;
            /** Report Projection Contract Version */
            report_projection_contract_version: string;
            /** Routing Policy Version */
            routing_policy_version: string;
        };
        /**
         * DeterministicProtectionFloor
         * @description The actions retained when an authorization can no longer admit new exposure.
         */
        DeterministicProtectionFloor: {
            /**
             * New Exposure Blocked
             * @constant
             */
            new_exposure_blocked: true;
            /** Retained Directions */
            retained_directions: ("REDUCE" | "EXIT")[];
        };
        /** DiagnosticObservation */
        DiagnosticObservation: {
            evidence: components["schemas"]["QualificationEvidence"];
            /** Rule Version */
            rule_version: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "CLEAR" | "RECURRENT" | "INSUFFICIENT" | "UNAVAILABLE";
        };
        /** DiagnosticPlan */
        DiagnosticPlan: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1.0.0";
            /** Planned Nodes */
            planned_nodes: string[];
            /** Rule Version */
            rule_version: string;
        };
        /**
         * DownsideGridRequalificationEvidence
         * @description Immutable historical and locked-forward proof for a changed downside grid.
         */
        DownsideGridRequalificationEvidence: {
            /** Action Policy Version Id */
            action_policy_version_id: string;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Evidence Id */
            evidence_id: string;
            /**
             * Historical Completed At
             * Format: date-time
             */
            historical_completed_at: string;
            /** Historical Out Of Sample Evidence Id */
            historical_out_of_sample_evidence_id: string;
            /** Locked Forward Confirmation Id */
            locked_forward_confirmation_id: string;
            /**
             * Locked Forward Confirmed At
             * Format: date-time
             */
            locked_forward_confirmed_at: string;
            /** Predecessor Authorization Id */
            predecessor_authorization_id: string;
            /** Predecessor Risk Budget Version Id */
            predecessor_risk_budget_version_id: string;
        };
        /** DrawdownBudget */
        DrawdownBudget: {
            /** Caution Ratio */
            caution_ratio: string;
            /** Defensive Ratio */
            defensive_ratio: string;
            /** Preservation Ratio */
            preservation_ratio: string;
        };
        /** ErroneousAlertReplay */
        ErroneousAlertReplay: {
            /** Alert Evidence Id */
            alert_evidence_id: string;
            /**
             * Alert Reproduced
             * @constant
             */
            alert_reproduced: false;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1.0.0";
            original_information: components["schemas"]["QualificationEvidence"];
            /** Original Information Digest */
            original_information_digest: string;
            /** Replay Id */
            replay_id: string;
            /** Replay Result Digest */
            replay_result_digest: string;
            /** Rule Version */
            rule_version: string;
        };
        /** EstablishedObligation */
        EstablishedObligation: {
            /** Basis Reference */
            basis_reference: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "REDUCE" | "EXIT";
            /** Obligation Id */
            obligation_id: string;
            /**
             * Quantity Status
             * @constant
             */
            quantity_status: "UNKNOWN";
        };
        /** EvidenceArtifact */
        EvidenceArtifact: {
            /** Artifact Id */
            artifact_id: string;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Content */
            content: string;
            /** Content Sha256 */
            content_sha256: string;
            /** License Id */
            license_id: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
            /** Version */
            version: string;
        };
        /** EvidenceBasis */
        EvidenceBasis: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1.0.0";
            /** Dependencies */
            dependencies: components["schemas"]["EvidenceArtifact"][];
            /** Dependency Windows */
            dependency_windows: components["schemas"]["EvidenceDependencyWindow"][];
            root_artifact: components["schemas"]["EvidenceArtifact"];
        };
        /**
         * EvidenceClock
         * @description The immutable fact, publication, acquisition, and validation clocks.
         */
        EvidenceClock: {
            /** Acquired At */
            acquired_at: string;
            /** Fact Effective At */
            fact_effective_at: string;
            /** Source Published At */
            source_published_at: string;
            /** Validated At */
            validated_at: string;
        };
        /** EvidenceDependencyWindow */
        EvidenceDependencyWindow: {
            /** Dependency Artifact Id */
            dependency_artifact_id: string;
            /** Parent Artifact Id */
            parent_artifact_id: string;
            /**
             * Required From
             * Format: date-time
             */
            required_from: string;
            /**
             * Required Until
             * Format: date-time
             */
            required_until: string;
        };
        /** ExcludedAccount */
        ExcludedAccount: {
            /** Account Id */
            account_id: string;
            /** Account Type */
            account_type: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "NOT_SELECTED" | "UNSUPPORTED_ACCOUNT_TYPE" | "UNKNOWN_ACCOUNT_TYPE";
        };
        /**
         * ExternalResult
         * @description The user-visible result expected from this original synthetic fixture.
         */
        ExternalResult: {
            correction_evidence?: components["schemas"]["CorrectionEvidence"] | null;
            governance?: components["schemas"]["GovernanceOutcome"] | null;
            /** Key Reasons */
            key_reasons: string[];
            /** Outcome Code */
            outcome_code: string;
            portfolio?: components["schemas"]["PortfolioAuthorizationOutcome"] | null;
            position?: components["schemas"]["PositionReconciliationOutcome"] | null;
            /** Summary */
            summary: string;
        };
        /** FormalCheckIdentity */
        FormalCheckIdentity: {
            /** Error Budget Id */
            error_budget_id?: string | null;
            /** Index */
            index: number;
            /**
             * Planned Nodes
             * @default []
             */
            planned_nodes: string[];
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            /**
             * Required Gates
             * @default []
             */
            required_gates: string[];
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Sequence Id */
            sequence_id: string;
        };
        /** FormalNodeDisposition */
        FormalNodeDisposition: {
            /** Check Index */
            check_index: number;
            evidence: components["schemas"]["QualificationEvidence"];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "EXECUTED_PASS" | "EXECUTED_FAIL" | "INSUFFICIENT" | "NOT_EXECUTED";
        };
        /**
         * FormalReport
         * @description Read-only delivery projection derived from one committed host event.
         */
        FormalReport: {
            access_scope?: components["schemas"]["ResultAccessScope"] | null;
            /** Business Object Id */
            business_object_id: string;
            /** Case Id */
            case_id: string;
            /** Corrects Event Id */
            corrects_event_id?: string | null;
            /** Event Id */
            event_id: string;
            evidence_clock: components["schemas"]["EvidenceClock"];
            /** Framework Run Id */
            framework_run_id: string;
            /** Generated At */
            generated_at: string;
            /** Knowledge Cutoff */
            knowledge_cutoff: string;
            /** Qualification Scope */
            qualification_scope: string;
            /** Report Version Id */
            report_version_id: string;
            result: components["schemas"]["ExternalResult"];
            /** Stage Results */
            stage_results: components["schemas"]["StageResult"][];
            /** Synthetic */
            synthetic: boolean;
            version_bundle: components["schemas"]["DecisionCaseVersionBundle"];
        };
        /** FrozenTask */
        FrozenTask: {
            /** Activation Id */
            activation_id: string | null;
            /** Decision Id */
            decision_id: string;
            /**
             * Freeze Status
             * @enum {string}
             */
            freeze_status: "APPROVED" | "DENIED";
            /**
             * Frozen At
             * Format: date-time
             */
            frozen_at: string;
            node: components["schemas"]["LegalTaskNode"];
            qualification_snapshot: components["schemas"]["QualificationRecord"] | null;
            /** Reasons */
            reasons: string[];
            scope: components["schemas"]["QualificationScope"];
            version: components["schemas"]["CapabilityVersion"];
        };
        /**
         * GateResult
         * @description One deterministic gate evaluated during a saved decision stage.
         */
        GateResult: {
            /** Gate Id */
            gate_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PASSED" | "FAILED" | "UNKNOWN";
        };
        /** GovernanceOutcome */
        GovernanceOutcome: {
            activation?: components["schemas"]["VersionActivation"] | null;
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "APPROVED" | "DENIED";
            policy_binding?: components["schemas"]["PolicyBinding"] | null;
            qualification?: components["schemas"]["QualificationRecord"] | null;
            /** Reasons */
            reasons: string[];
            recorded_alert_replay?: components["schemas"]["RecordedAlertReplay"] | null;
            registered_requalification?: components["schemas"]["RegisteredRequalificationApplication"] | null;
            task?: components["schemas"]["FrozenTask"] | null;
            task_node?: components["schemas"]["RegisteredTaskNode"] | null;
            usage?: components["schemas"]["TaskUsage"] | null;
        };
        /**
         * IssuerExposure
         * @description Current issuer exposure aggregates market value only after account facts stay separate.
         */
        IssuerExposure: {
            /** Account Ids */
            account_ids: string[];
            /** Current Market Exposure */
            current_market_exposure: string | null;
            /** Issuer Id */
            issuer_id: string;
            /** Valuation Currency */
            valuation_currency: string;
        };
        /** LegalTaskNode */
        LegalTaskNode: {
            /**
             * Deterministic Obligations
             * @default []
             */
            deterministic_obligations: components["schemas"]["EstablishedObligation"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "MONTHLY" | "DAILY" | "RENEWAL";
            /**
             * Knowledge Cutoff
             * Format: date-time
             */
            knowledge_cutoff: string;
            /** Node Id */
            node_id: string;
            /**
             * Retained Objects
             * @default []
             */
            retained_objects: components["schemas"]["RetainedObjectReference"][];
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Task Identity */
            task_identity: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
        };
        /**
         * NormalMarketSessionEvidence
         * @description One immutable normal market session from a versioned synthetic calendar.
         */
        NormalMarketSessionEvidence: {
            /**
             * Closed At
             * Format: date-time
             */
            closed_at: string;
            /** Evidence Id */
            evidence_id: string;
            /** Market Calendar Version Id */
            market_calendar_version_id: string;
            /** Market Session Ordinal */
            market_session_ordinal: number;
            /**
             * Normal
             * @constant
             */
            normal: true;
        };
        /** OpaqueRequestErrorDto */
        OpaqueRequestErrorDto: {
            /**
             * Detail
             * @default request is not permitted
             * @constant
             */
            detail: "request is not permitted";
        };
        /**
         * PersonalRiskBudget
         * @description The explicit synthetic risk configuration bound to exactly six calendar months.
         */
        PersonalRiskBudget: {
            /** Action Policy Version Id */
            action_policy_version_id: string;
            cash: components["schemas"]["CashBudget"];
            concentration: components["schemas"]["TwoThresholdBudget"];
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1.0.0";
            /** Downside Grid */
            downside_grid: string[];
            drawdown: components["schemas"]["DrawdownBudget"];
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Generator Version */
            generator_version: string;
            protection_floor: components["schemas"]["DeterministicProtectionFloor"];
            /** Seed */
            seed: number;
            stress: components["schemas"]["TwoThresholdBudget"];
            /**
             * Synthetic
             * @constant
             */
            synthetic: true;
            /** Version Id */
            version_id: string;
        };
        /**
         * PolicyBinding
         * @description Frozen scoped policy input, independent of whether authority was obtained.
         */
        PolicyBinding: {
            scope: components["schemas"]["QualificationScope"];
            version: components["schemas"]["CapabilityVersion"];
        };
        /**
         * PortfolioAuthorization
         * @description The append-only risk-budget authorization retained by a formal report.
         */
        PortfolioAuthorization: {
            /** Authorization Id */
            authorization_id: string;
            confirmation: components["schemas"]["PortfolioConfirmation"];
            /** Previous Authorization Id */
            previous_authorization_id?: string | null;
            proposal: components["schemas"]["PortfolioProposal"];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** PortfolioAuthorizationOutcome */
        PortfolioAuthorizationOutcome: {
            authorization?: components["schemas"]["PortfolioAuthorization"] | null;
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "PREVIEWED" | "APPROVED" | "DENIED";
            preview?: components["schemas"]["PortfolioPreview"] | null;
            /** Reasons */
            reasons: string[];
            usage?: components["schemas"]["PortfolioAuthorizationUsage"] | null;
        };
        /** PortfolioAuthorizationUsage */
        PortfolioAuthorizationUsage: {
            /** Allowed */
            allowed: boolean;
            authorization_snapshot: components["schemas"]["PortfolioAuthorization"];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Reasons */
            reasons: string[];
            /**
             * Requested Action
             * @enum {string}
             */
            requested_action: "NEW_EXPOSURE" | "DETERMINISTIC_PROTECTION";
            retained_protection_floor: components["schemas"]["DeterministicProtectionFloor"];
            /** Unfinished Cash Obligations */
            unfinished_cash_obligations: components["schemas"]["DatedCashObligation"][];
        };
        /** PortfolioConfirmation */
        PortfolioConfirmation: {
            /** Confirmation Id */
            confirmation_id: string;
            /**
             * Confirmed
             * @constant
             */
            confirmed: true;
            /**
             * Confirmed At
             * Format: date-time
             */
            confirmed_at: string;
            downside_grid_requalification?: components["schemas"]["DownsideGridRequalificationEvidence"] | null;
            /** Portfolio Id */
            portfolio_id: string;
            relaxation_evidence?: components["schemas"]["RiskBudgetRelaxationEvidence"] | null;
            /** Risk Budget Version Id */
            risk_budget_version_id: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** User Id */
            user_id: string;
        };
        /** PortfolioPreview */
        PortfolioPreview: {
            /** Blocking Account Ids */
            blocking_account_ids: string[];
            /**
             * Blocking Accounts
             * @default []
             */
            blocking_accounts: components["schemas"]["ExcludedAccount"][];
            /** Excluded Accounts */
            excluded_accounts: components["schemas"]["ExcludedAccount"][];
            /** Included Account Ids */
            included_account_ids: string[];
            /** Included Accounts */
            included_accounts: components["schemas"]["CompleteAccountSnapshot"][];
            /** Portfolio Id */
            portfolio_id: string;
            /** Snapshot Id */
            snapshot_id: string;
        };
        /**
         * PortfolioProposal
         * @description The complete selection and policy snapshot shown before a user confirmation.
         */
        PortfolioProposal: {
            activation_snapshot?: components["schemas"]["PortfolioSnapshot"] | null;
            /**
             * Cash Obligations
             * @default []
             */
            cash_obligations: components["schemas"]["DatedCashObligation"][];
            /** Portfolio Id */
            portfolio_id: string;
            risk_budget: components["schemas"]["PersonalRiskBudget"];
            snapshot: components["schemas"]["PortfolioSnapshot"];
        };
        /**
         * PortfolioSnapshot
         * @description The common-cutoff universe from which full accounts can be selected.
         */
        PortfolioSnapshot: {
            /** Accounts */
            accounts: components["schemas"]["CompleteAccountSnapshot"][];
            /**
             * Cutoff At
             * Format: date-time
             */
            cutoff_at: string;
            /** Selected Account Ids */
            selected_account_ids: string[];
            /** Snapshot Id */
            snapshot_id: string;
        };
        /**
         * PositionActionUnit
         * @description One account-local action quantity, never an issuer-level order instruction.
         */
        PositionActionUnit: {
            /** Account Id */
            account_id: string;
            /** Account Type */
            account_type: string;
            /** Broker Sellable Quantity */
            broker_sellable_quantity: string | null;
            /** Currency */
            currency: string;
            /**
             * Exact Quantity Status
             * @enum {string}
             */
            exact_quantity_status: "AVAILABLE" | "BLOCKED";
            /** Exact Statistical Action Quantity */
            exact_statistical_action_quantity: string | null;
            /** Frozen Quantity */
            frozen_quantity: string | null;
            /** Issuer Id */
            issuer_id: string;
            /** Lifecycle Id */
            lifecycle_id: string;
            /** Open Sell Order Quantity */
            open_sell_order_quantity: string | null;
            /**
             * Origin
             * @enum {string}
             */
            origin: "SYSTEM" | "EXTERNAL";
            position_evidence: components["schemas"]["PositionEvidence"];
            /** Position Id */
            position_id: string;
            /** Reasons */
            reasons: string[];
            /** Restricted Quantity */
            restricted_quantity: string | null;
            /** Security Id */
            security_id: string;
            /** Total Quantity */
            total_quantity: string | null;
            /** Unsettled Quantity */
            unsettled_quantity: string | null;
        };
        /**
         * PositionAffectedScope
         * @description The account/security scope for a conflict and its statistical consequence.
         */
        PositionAffectedScope: {
            /** Account Id */
            account_id?: string | null;
            /** Fields */
            fields: string[];
            /** Security Id */
            security_id?: string | null;
        };
        /**
         * PositionEvidence
         * @description Source provenance remains explicit even when an incomplete fact is retained.
         */
        PositionEvidence: {
            /** Business Effective At */
            business_effective_at: string | null;
            /** Complete Through At */
            complete_through_at: string | null;
            /** Cutoff At */
            cutoff_at: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Locally Acquired At */
            locally_acquired_at: string | null;
            /** Source */
            source: string | null;
            /** Source Observed At */
            source_observed_at: string | null;
            /** Source Version */
            source_version: string | null;
            /** Validated At */
            validated_at: string | null;
        };
        /**
         * PositionEvidenceClock
         * @description The source clock retained with a displayed position-state snapshot.
         */
        PositionEvidenceClock: {
            /** Business Effective At */
            business_effective_at: string | null;
            /** Locally Acquired At */
            locally_acquired_at: string | null;
            /** Source Observed At */
            source_observed_at: string | null;
            /** Validated At */
            validated_at: string | null;
        };
        /**
         * PositionFactConflict
         * @description An unreconciled source fact; it never selects one conflicting value.
         */
        PositionFactConflict: {
            affected_scope: components["schemas"]["PositionAffectedScope"];
            /** Blocks Exact Statistical Quantity */
            blocks_exact_statistical_quantity: boolean;
            /** Code */
            code: string;
            /** Conflict Id */
            conflict_id: string;
        };
        /**
         * PositionReconciliationOutcome
         * @description The host-owned result appended after a valid frozen framework output.
         */
        PositionReconciliationOutcome: {
            /** Conflicts */
            conflicts: components["schemas"]["PositionFactConflict"][];
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "RECONCILED" | "CONFLICTED";
            /** Reasons */
            reasons: string[];
            snapshot: components["schemas"]["ReconciledPositionSnapshot"];
        };
        /** QualificationEvidence */
        QualificationEvidence: {
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            basis?: components["schemas"]["EvidenceBasis"] | null;
            certified_substitution?: components["schemas"]["CertifiedBasisSubstitution"] | null;
            diagnostic_plan?: components["schemas"]["DiagnosticPlan"] | null;
            /** Digest */
            digest: string;
            /**
             * Evaluation End
             * Format: date-time
             */
            evaluation_end: string;
            /** Evidence Id */
            evidence_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            formal_check?: components["schemas"]["FormalCheckIdentity"] | null;
            /**
             * Gate Results
             * @default []
             */
            gate_results: components["schemas"]["QualificationGate"][];
            /** Generator Version */
            generator_version: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "QUALIFICATION_PASS" | "DIAGNOSTIC_ALERT" | "INSUFFICIENT_EVIDENCE" | "REQUIRED_PREMISE_UNVERIFIABLE" | "ORIGINAL_BASIS_INVALID" | "RESTORATION_DECISION" | "ORIGINAL_BASIS_RESTORED" | "REQUALIFICATION_PASS" | "HISTORICAL_OOS_PASS" | "LOCKED_FORWARD_PASS" | "FORMAL_CHECK" | "FORMAL_NODE_NOT_EXECUTED" | "DIAGNOSTIC_CLEAR" | "DIAGNOSTIC_RECURRENT" | "DIAGNOSTIC_INSUFFICIENT" | "DIAGNOSTIC_UNAVAILABLE" | "ALERT_CLOSURE" | "ALERT_PROVEN_ERRONEOUS" | "ALERT_TRANSFERRED" | "ALERT_ARCHIVED" | "CERTIFIED_BASIS_SUBSTITUTION" | "STATE_ACTIVITY_RESTORED" | "REQUALIFICATION_APPLICATION_REGISTERED" | "ALERT_REPLAY_RECORDED";
            /** Maturity Sufficient */
            maturity_sufficient?: boolean | null;
            /** Requalification Application Id */
            requalification_application_id?: string | null;
            /** Requalification Population Id */
            requalification_population_id?: string | null;
            /** Requalification Registration Digest */
            requalification_registration_digest?: string | null;
            /** Resolves Evidence Id */
            resolves_evidence_id?: string | null;
            /** Restored Authorization Digest */
            restored_authorization_digest?: string | null;
            /** Reviewed Alert Digest */
            reviewed_alert_digest?: string | null;
            scope: components["schemas"]["QualificationScope"];
            /** Seed */
            seed: number;
            /** State Activity End */
            state_activity_end?: string | null;
            /**
             * Synthetic
             * @constant
             */
            synthetic: true;
            version: components["schemas"]["CapabilityVersion"];
        };
        /** QualificationGate */
        QualificationGate: {
            /** Gate Id */
            gate_id: string;
            /** Passed */
            passed: boolean;
        };
        /**
         * QualificationPolicy
         * @description Explicit D0 policy input, never a default for personal authorization.
         */
        QualificationPolicy: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1.0.0";
            /** Diagnostic Clear Node Count */
            diagnostic_clear_node_count?: number | null;
            /** Evaluation Max Age Months */
            evaluation_max_age_months: number;
            /** Generator Version */
            generator_version: string;
            /** Policy Version */
            policy_version: string;
            /** Require State Activity */
            require_state_activity: boolean;
            /** Seed */
            seed: number;
            /** State Activity Max Age Months */
            state_activity_max_age_months: number;
            /**
             * Synthetic
             * @constant
             */
            synthetic: true;
        };
        /** QualificationRecord */
        QualificationRecord: {
            /**
             * Alert Closures
             * @default []
             */
            alert_closures: components["schemas"]["AlertClosure"][];
            /**
             * Alerts
             * @default []
             */
            alerts: components["schemas"]["QualificationEvidence"][];
            authorization_evidence: components["schemas"]["QualificationEvidence"] | null;
            /** Authorization Id */
            authorization_id: string | null;
            /** Authorization Terminated At */
            authorization_terminated_at?: string | null;
            /** Cause */
            cause: string;
            /** Decision Id */
            decision_id: string;
            evidence: components["schemas"]["QualificationEvidence"];
            formal_evidence?: components["schemas"]["QualificationEvidence"] | null;
            /**
             * Formal Node Dispositions
             * @default []
             */
            formal_node_dispositions: components["schemas"]["FormalNodeDisposition"][];
            formal_passing_evidence?: components["schemas"]["QualificationEvidence"] | null;
            /** Last Formal Node */
            last_formal_node?: string | null;
            /** Previous Decision Id */
            previous_decision_id?: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            requalification?: components["schemas"]["RequalificationProof"] | null;
            /**
             * Restoration Evidence
             * @default []
             */
            restoration_evidence: components["schemas"]["QualificationEvidence"][];
            /**
             * Restrictions
             * @default []
             */
            restrictions: components["schemas"]["QualificationRestriction"][];
            scope: components["schemas"]["QualificationScope"];
            state_activity_evidence?: components["schemas"]["QualificationEvidence"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "NOT_OBTAINED" | "VALID" | "AT_RISK" | "SUSPENDED" | "REVOKED";
            version: components["schemas"]["CapabilityVersion"];
        };
        /** QualificationRestriction */
        QualificationRestriction: {
            /**
             * Cause
             * @enum {string}
             */
            cause: "REQUIRED_PREMISE_UNVERIFIABLE" | "ORIGINAL_BASIS_INVALID" | "EVIDENCE_EXPIRED" | "STATE_ACTIVITY_EXPIRED" | "FORMAL_PERFORMANCE_FAILURE";
            evidence: components["schemas"]["QualificationEvidence"];
        };
        /** QualificationScope */
        QualificationScope: {
            /** Account Ids */
            account_ids: string[];
            /** Account Type */
            account_type: string;
            /** Board */
            board: string;
            /** Capability */
            capability: string;
            /**
             * Evidence Level
             * @constant
             */
            evidence_level: "D0";
            /** Holding Age Domain */
            holding_age_domain?: string | null;
            /** Market State */
            market_state: string;
            /** Portfolio Scope */
            portfolio_scope?: string | null;
            /** Probability Grid */
            probability_grid?: string | null;
            /** Purpose */
            purpose: string;
            /** Renewal Ordinal */
            renewal_ordinal?: string | null;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** User Id */
            user_id: string;
        };
        /**
         * ReauthenticationVerificationDto
         * @description Pydantic transport contract for a completed recent reauthentication.
         */
        ReauthenticationVerificationDto: {
            /** Credential Id */
            credential_id: string;
        };
        /**
         * ReconciledPositionSnapshot
         * @description A read-only, same-cutoff result derived from broker facts and their ledgers.
         */
        ReconciledPositionSnapshot: {
            /** Action Units */
            action_units: components["schemas"]["PositionActionUnit"][];
            /** Authoritative Ledger */
            authoritative_ledger: components["schemas"]["AuthoritativeLedgerEntry"][];
            /** Cash States */
            cash_states: components["schemas"]["AccountCashState"][];
            /**
             * Cutoff At
             * Format: date-time
             */
            cutoff_at: string;
            evidence_clock: components["schemas"]["PositionEvidenceClock"];
            /** Execution Restrictions */
            execution_restrictions: components["schemas"]["AccountExecutionRestriction"][];
            /** Issuer Exposures */
            issuer_exposures: components["schemas"]["IssuerExposure"][];
            snapshot_evidence: components["schemas"]["PositionEvidence"];
            /** Snapshot Id */
            snapshot_id: string;
            /** Snapshot Source */
            snapshot_source: string | null;
            /** Total Account Equity */
            total_account_equity: string | null;
            /** Unfinished Orders */
            unfinished_orders: components["schemas"]["AccountOpenOrder"][];
            /** User Annotations */
            user_annotations: components["schemas"]["UserPositionAnnotation"][];
            /** Valuation Currency */
            valuation_currency: string;
        };
        /** RecordedAlertReplay */
        RecordedAlertReplay: {
            /** Decision Id */
            decision_id: string;
            evidence: components["schemas"]["QualificationEvidence"];
            /** Previous Qualification Decision Id */
            previous_qualification_decision_id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            replay: components["schemas"]["ErroneousAlertReplay"];
            scope: components["schemas"]["QualificationScope"];
            version: components["schemas"]["CapabilityVersion"];
        };
        /** RegisteredRequalificationApplication */
        RegisteredRequalificationApplication: {
            application: components["schemas"]["RequalificationApplication"];
            /** Decision Id */
            decision_id: string;
            evidence: components["schemas"]["QualificationEvidence"];
            /** Previous Qualification Decision Id */
            previous_qualification_decision_id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            scope: components["schemas"]["QualificationScope"];
            version: components["schemas"]["CapabilityVersion"];
        };
        /** RegisteredTaskNode */
        RegisteredTaskNode: {
            /** Decision Id */
            decision_id: string;
            node: components["schemas"]["LegalTaskNode"];
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            scope: components["schemas"]["QualificationScope"];
        };
        /** RequalificationApplication */
        RequalificationApplication: {
            /** Application Id */
            application_id: string;
            forward_registration: components["schemas"]["RequalificationPopulationRegistration"];
            /** Frozen Version Digest */
            frozen_version_digest: string;
            historical_registration: components["schemas"]["RequalificationPopulationRegistration"];
            /**
             * Locked At
             * Format: date-time
             */
            locked_at: string;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
        };
        /** RequalificationMember */
        RequalificationMember: {
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /**
             * Matured At
             * Format: date-time
             */
            matured_at: string;
            /** Member Id */
            member_id: string;
            /** Outcome Digest */
            outcome_digest: string;
            /**
             * Prediction Frozen At
             * Format: date-time
             */
            prediction_frozen_at: string;
        };
        /** RequalificationPopulation */
        RequalificationPopulation: {
            /** Evidence Id */
            evidence_id: string;
            /** Frozen Version Digest */
            frozen_version_digest: string;
            /** Gate Results */
            gate_results: components["schemas"]["QualificationGate"][];
            /** Members */
            members: components["schemas"]["RequalificationMember"][];
            /** Population Id */
            population_id: string;
            /** Registered Member Ids */
            registered_member_ids: string[];
            /** Required Gates */
            required_gates: string[];
        };
        /** RequalificationPopulationRegistration */
        RequalificationPopulationRegistration: {
            /** Application Id */
            application_id: string;
            /** Digest */
            digest: string;
            /** Frozen Version Digest */
            frozen_version_digest: string;
            /**
             * Locked At
             * Format: date-time
             */
            locked_at: string;
            /** Population Id */
            population_id: string;
            /**
             * Population Kind
             * @enum {string}
             */
            population_kind: "HISTORICAL" | "FORWARD";
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            /** Registered Member Ids */
            registered_member_ids: string[];
            /** Required Gates */
            required_gates: string[];
        };
        /** RequalificationProof */
        RequalificationProof: {
            /** Application Id */
            application_id: string;
            /**
             * First Prediction Frozen At
             * Format: date-time
             */
            first_prediction_frozen_at: string;
            forward_evidence: components["schemas"]["QualificationEvidence"];
            forward_population?: components["schemas"]["RequalificationPopulation"] | null;
            forward_registration?: components["schemas"]["RequalificationPopulationRegistration"] | null;
            /** Frozen Version Digest */
            frozen_version_digest?: string | null;
            historical_evidence: components["schemas"]["QualificationEvidence"];
            historical_population?: components["schemas"]["RequalificationPopulation"] | null;
            historical_registration?: components["schemas"]["RequalificationPopulationRegistration"] | null;
            /**
             * Locked At
             * Format: date-time
             */
            locked_at: string;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
        };
        /**
         * ResultAccessScope
         * @description Immutable ownership and visibility bound before a scoped case is executed.
         */
        ResultAccessScope: {
            /** Account Ids */
            account_ids: string[];
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1.0.0";
            /** User Id */
            user_id: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "USER" | "SHADOW";
        };
        /** RetainedObjectReference */
        RetainedObjectReference: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "CONCLUSION" | "CONTRACT" | "EVIDENCE" | "EVALUATION";
            /** Object Id */
            object_id: string;
        };
        /** RetainedTaskRelation */
        RetainedTaskRelation: {
            /** Activation Id */
            activation_id: string | null;
            /**
             * Deterministic Obligations
             * @default []
             */
            deterministic_obligations: components["schemas"]["EstablishedObligation"][];
            /**
             * Knowledge Cutoff
             * Format: date-time
             */
            knowledge_cutoff: string;
            /** Node Id */
            node_id: string;
            original_version: components["schemas"]["CapabilityVersion"];
            /** Qualification Decision Id */
            qualification_decision_id: string | null;
            /**
             * Retained Objects
             * @default []
             */
            retained_objects: components["schemas"]["RetainedObjectReference"][];
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Task Decision Id */
            task_decision_id: string;
            /** Task Identity */
            task_identity: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
        };
        /**
         * RiskBudgetRelaxationEvidence
         * @description Synthetic proof required before a successor can relax a frozen risk budget.
         */
        RiskBudgetRelaxationEvidence: {
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Evidence Id */
            evidence_id: string;
            /**
             * Monthly Selection Cutoff At
             * Format: date-time
             */
            monthly_selection_cutoff_at: string;
            /**
             * Normal From At
             * Format: date-time
             */
            normal_from_at: string;
            /** Normal Market Sessions */
            normal_market_sessions: components["schemas"]["NormalMarketSessionEvidence"][];
            /**
             * Normal Through At
             * Format: date-time
             */
            normal_through_at: string;
            /** Predecessor Authorization Id */
            predecessor_authorization_id: string;
            /** Predecessor Risk Budget Version Id */
            predecessor_risk_budget_version_id: string;
        };
        /**
         * SafetyCapabilitiesDiagnosticDto
         * @description Machine-readable official-project safety invariants.
         */
        SafetyCapabilitiesDiagnosticDto: {
            /** Order Writing */
            order_writing: boolean;
            /** Public Recommendation Service */
            public_recommendation_service: boolean;
            /** Single User */
            single_user: boolean;
        };
        /**
         * SessionRefreshDto
         * @description Pydantic transport contract for a CSRF-protected idle-session refresh.
         */
        SessionRefreshDto: {
            /** Status */
            status: string;
        };
        /**
         * StageResult
         * @description A phase-specific outcome; lifecycle states have no global terminal meaning.
         */
        StageResult: {
            /** Gate Results */
            gate_results: components["schemas"]["GateResult"][];
            /**
             * Phase
             * @enum {string}
             */
            phase: "FRAMEWORK_RUN" | "HOST_VALIDATION" | "BUSINESS_DECISION" | "QUALIFICATION" | "PORTFOLIO_AUTHORIZATION" | "POSITION_RECONCILIATION" | "ADJUDICATION_LIFECYCLE" | "VALIDITY_LIFECYCLE" | "EXECUTION_LIFECYCLE" | "COMMIT_RECONCILIATION" | "BUSINESS_COMMIT" | "PUBLICATION" | "NOTIFICATION" | "CORRECTION";
            /** Reasons */
            reasons: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "CREATED" | "RUNNING" | "WAITING" | "SUCCEEDED" | "REJECTED" | "ABSTAINED" | "FAILED" | "PENDING" | "EXPIRED" | "EXECUTION_BLOCKED" | "UNKNOWN" | "CANCELLED";
        };
        /** TaskUsage */
        TaskUsage: {
            /** Allowed */
            allowed: boolean;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            qualification_snapshot: components["schemas"]["QualificationRecord"] | null;
            /** Reasons */
            reasons: string[];
            task_snapshot: components["schemas"]["FrozenTask"];
        };
        /** TwoThresholdBudget */
        TwoThresholdBudget: {
            /** Hard Ratio */
            hard_ratio: string;
            /** Target Ratio */
            target_ratio: string;
        };
        /** UserFact */
        UserFact: {
            /**
             * Authoritative Execution
             * @default false
             * @constant
             */
            authoritative_execution: false;
            /** Choice */
            choice: ("ACCEPT" | "DECLINE" | "DEFER") | null;
            /** Declaration */
            declaration: string | null;
            /** Event Id */
            event_id: string;
            /** Fact Id */
            fact_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "VIEWED" | "ACKNOWLEDGED" | "CONFIRMED" | "EXECUTION_DECLARED";
            /**
             * Reconciliation Status
             * @enum {string}
             */
            reconciliation_status: "NOT_APPLICABLE" | "PENDING";
            /** Recorded At */
            recorded_at: string;
            /** Report Version Id */
            report_version_id: string;
            /**
             * Synthetic
             * @default true
             * @constant
             */
            synthetic: true;
        };
        /** UserFactRequest */
        UserFactRequest: {
            /** Choice */
            choice?: ("ACCEPT" | "DECLINE" | "DEFER") | null;
            /** Declaration */
            declaration?: ("PREPARING" | "REPORTED_SUBMITTED" | "REPORTED_PARTIAL" | "REPORTED_FILLED" | "REPORTED_CANCELLED" | "UNABLE") | null;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "VIEWED" | "ACKNOWLEDGED" | "CONFIRMED" | "EXECUTION_DECLARED";
        };
        /**
         * UserPositionAnnotation
         * @description A user-supplied note retained separately from broker-authoritative records.
         */
        UserPositionAnnotation: {
            /** Account Id */
            account_id: string;
            /** Annotation Id */
            annotation_id: string;
            /** Claimed Cost Basis */
            claimed_cost_basis?: string | null;
            /** Claimed Total Quantity */
            claimed_total_quantity?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Note */
            note: string;
            /** Security Id */
            security_id: string;
        };
        /** VersionActivation */
        VersionActivation: {
            /** Decision Id */
            decision_id: string;
            first_node: components["schemas"]["LegalTaskNode"];
            /** Previous Activation Id */
            previous_activation_id: string | null;
            previous_version: components["schemas"]["CapabilityVersion"] | null;
            qualification_snapshot: components["schemas"]["QualificationRecord"];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Retained Task Ids */
            retained_task_ids: string[];
            /**
             * Retained Tasks
             * @default []
             */
            retained_tasks: components["schemas"]["RetainedTaskRelation"][];
            scope: components["schemas"]["QualificationScope"];
            version: components["schemas"]["CapabilityVersion"];
        };
        /**
         * VersionDiagnosticDto
         * @description Pydantic-only transport contract for the public diagnostic interface.
         */
        VersionDiagnosticDto: {
            /** Application Version */
            application_version: string;
            /** M Agent Release Commit */
            m_agent_release_commit: string;
            /** M Agent Version */
            m_agent_version: string;
            /** M Agent Wheel Sha256 */
            m_agent_wheel_sha256: string;
            /** M Agent Wheel Url */
            m_agent_wheel_url: string;
            /** Source Sha */
            source_sha: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authentication_options_api_v1_auth_passkeys_authentication_options_post: {
        parameters: {
            query?: never;
            header?: {
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDto"];
                };
            };
            /** @description No enrolled passkey is available */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    authentication_verify_api_v1_auth_passkeys_authentication_verify_post: {
        parameters: {
            query?: never;
            header?: {
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationVerificationDto"];
                };
            };
            /** @description Authentication verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    reauthentication_options_api_v1_auth_passkeys_reauthentication_options_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDto"];
                };
            };
            /** @description Recent authenticated session required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    reauthentication_verify_api_v1_auth_passkeys_reauthentication_verify_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReauthenticationVerificationDto"];
                };
            };
            /** @description Reauthentication verification failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    registration_options_api_v1_auth_passkeys_registration_options_post: {
        parameters: {
            query?: never;
            header: {
                "X-Host-Console-Grant": string;
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDto"];
                };
            };
            /** @description Host console grant required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    registration_verify_api_v1_auth_passkeys_registration_verify_post: {
        parameters: {
            query?: never;
            header?: {
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Registration verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    logout_api_v1_auth_session_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin, CSRF token, or session was invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    refresh_session_api_v1_auth_session_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRefreshDto"];
                };
            };
            /** @description Origin, CSRF token, or session was invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    safety_capabilities_diagnostic_api_v1_diagnostics_safety_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyCapabilitiesDiagnosticDto"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    version_diagnostic_api_v1_diagnostics_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDiagnosticDto"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    formal_report_api_v1_reports__report_version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_version_id: string;
            };
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormalReport"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Formal report not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    report_user_facts_api_v1_reports__report_version_id__facts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_version_id: string;
            };
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFact"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    record_report_user_fact_api_v1_reports__report_version_id__facts_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path: {
                report_version_id: string;
            };
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserFactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFact"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
}
