/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/passkeys/authentication/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentication Options */
        post: operations["authentication_options_api_v1_auth_passkeys_authentication_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/authentication/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentication Verify */
        post: operations["authentication_verify_api_v1_auth_passkeys_authentication_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/reauthentication/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthentication Options */
        post: operations["reauthentication_options_api_v1_auth_passkeys_reauthentication_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/reauthentication/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthentication Verify */
        post: operations["reauthentication_verify_api_v1_auth_passkeys_reauthentication_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/registration/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registration Options */
        post: operations["registration_options_api_v1_auth_passkeys_registration_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/registration/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registration Verify */
        post: operations["registration_verify_api_v1_auth_passkeys_registration_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Logout */
        delete: operations["logout_api_v1_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Session */
        post: operations["refresh_session_api_v1_auth_session_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/safety-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Safety Capabilities Diagnostic
         * @description Report static safety boundaries without exposing a product action.
         */
        get: operations["safety_capabilities_diagnostic_api_v1_diagnostics_safety_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version Diagnostic */
        get: operations["version_diagnostic_api_v1_diagnostics_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Formal Report */
        get: operations["formal_report_api_v1_reports__report_version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_version_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report User Facts */
        get: operations["report_user_facts_api_v1_reports__report_version_id__facts_get"];
        put?: never;
        /** Record Report User Fact */
        post: operations["record_report_user_fact_api_v1_reports__report_version_id__facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthenticationVerificationDto
         * @description Pydantic transport contract for a completed passkey authentication.
         */
        AuthenticationVerificationDto: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** ChallengeDto */
        ChallengeDto: {
            /** Challenge Id */
            challenge_id: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
        };
        /**
         * CorrectionEvidence
         * @description New authoritative synthetic facts, distinct from the original Run's evidence.
         */
        CorrectionEvidence: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "2.0.0";
            /** Corrected Statement */
            corrected_statement: string;
            /** Corrects Evidence Id */
            corrects_evidence_id: string;
            /** Decision Formed At */
            decision_formed_at: string;
            evidence_clock: components["schemas"]["EvidenceClock"];
            /** Evidence Id */
            evidence_id: string;
            /** Knowledge Cutoff */
            knowledge_cutoff: string;
            /** Original Statement */
            original_statement: string;
            /** Reason */
            reason: string;
            /** Source */
            source: string;
        };
        /** CredentialRequest */
        CredentialRequest: {
            /** Challenge Id */
            challenge_id: string;
            /** Credential */
            credential: {
                [key: string]: unknown;
            };
        };
        /**
         * DecisionCaseVersionBundle
         * @description The complete version set that participates in replay identity.
         */
        DecisionCaseVersionBundle: {
            /** Agent Definition Id */
            agent_definition_id: string;
            /** Agent Definition Version */
            agent_definition_version: string;
            /** Case Contract Version */
            case_contract_version: string;
            /** Host Application Version */
            host_application_version: string;
            /** Host Contract Version */
            host_contract_version: string;
            /** Host Source Sha */
            host_source_sha: string;
            /** M Agent Release Commit */
            m_agent_release_commit: string;
            /** M Agent Version */
            m_agent_version: string;
            /** M Agent Wheel Sha256 */
            m_agent_wheel_sha256: string;
            /** M Agent Wheel Url */
            m_agent_wheel_url: string;
            /** Model Adapter Id */
            model_adapter_id: string;
            /** Output Contract Version */
            output_contract_version: string;
            /** Report Projection Contract Version */
            report_projection_contract_version: string;
            /** Routing Policy Version */
            routing_policy_version: string;
        };
        /**
         * EvidenceClock
         * @description The immutable fact, publication, acquisition, and validation clocks.
         */
        EvidenceClock: {
            /** Acquired At */
            acquired_at: string;
            /** Fact Effective At */
            fact_effective_at: string;
            /** Source Published At */
            source_published_at: string;
            /** Validated At */
            validated_at: string;
        };
        /**
         * ExternalResult
         * @description The user-visible result expected from this original synthetic fixture.
         */
        ExternalResult: {
            correction_evidence?: components["schemas"]["CorrectionEvidence"] | null;
            /** Key Reasons */
            key_reasons: string[];
            /** Outcome Code */
            outcome_code: string;
            /** Summary */
            summary: string;
        };
        /**
         * FormalReport
         * @description Read-only delivery projection derived from one committed host event.
         */
        FormalReport: {
            access_scope?: components["schemas"]["ResultAccessScope"] | null;
            /** Business Object Id */
            business_object_id: string;
            /** Case Id */
            case_id: string;
            /** Corrects Event Id */
            corrects_event_id?: string | null;
            /** Event Id */
            event_id: string;
            evidence_clock: components["schemas"]["EvidenceClock"];
            /** Framework Run Id */
            framework_run_id: string;
            /** Generated At */
            generated_at: string;
            /** Knowledge Cutoff */
            knowledge_cutoff: string;
            /** Qualification Scope */
            qualification_scope: string;
            /** Report Version Id */
            report_version_id: string;
            result: components["schemas"]["ExternalResult"];
            /** Stage Results */
            stage_results: components["schemas"]["StageResult"][];
            /** Synthetic */
            synthetic: boolean;
            version_bundle: components["schemas"]["DecisionCaseVersionBundle"];
        };
        /**
         * GateResult
         * @description One deterministic gate evaluated during a saved decision stage.
         */
        GateResult: {
            /** Gate Id */
            gate_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PASSED" | "FAILED" | "UNKNOWN";
        };
        /** OpaqueRequestErrorDto */
        OpaqueRequestErrorDto: {
            /**
             * Detail
             * @default request is not permitted
             * @constant
             */
            detail: "request is not permitted";
        };
        /**
         * ReauthenticationVerificationDto
         * @description Pydantic transport contract for a completed recent reauthentication.
         */
        ReauthenticationVerificationDto: {
            /** Credential Id */
            credential_id: string;
        };
        /**
         * ResultAccessScope
         * @description Immutable ownership and visibility bound before a scoped case is executed.
         */
        ResultAccessScope: {
            /** Account Ids */
            account_ids: string[];
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1.0.0";
            /** User Id */
            user_id: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "USER" | "SHADOW";
        };
        /**
         * SafetyCapabilitiesDiagnosticDto
         * @description Machine-readable official-project safety invariants.
         */
        SafetyCapabilitiesDiagnosticDto: {
            /** Order Writing */
            order_writing: boolean;
            /** Public Recommendation Service */
            public_recommendation_service: boolean;
            /** Single User */
            single_user: boolean;
        };
        /**
         * SessionRefreshDto
         * @description Pydantic transport contract for a CSRF-protected idle-session refresh.
         */
        SessionRefreshDto: {
            /** Status */
            status: string;
        };
        /**
         * StageResult
         * @description A phase-specific outcome; lifecycle states have no global terminal meaning.
         */
        StageResult: {
            /** Gate Results */
            gate_results: components["schemas"]["GateResult"][];
            /**
             * Phase
             * @enum {string}
             */
            phase: "FRAMEWORK_RUN" | "HOST_VALIDATION" | "BUSINESS_DECISION" | "ADJUDICATION_LIFECYCLE" | "VALIDITY_LIFECYCLE" | "EXECUTION_LIFECYCLE" | "COMMIT_RECONCILIATION" | "BUSINESS_COMMIT" | "PUBLICATION" | "NOTIFICATION" | "CORRECTION";
            /** Reasons */
            reasons: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "CREATED" | "RUNNING" | "WAITING" | "SUCCEEDED" | "REJECTED" | "ABSTAINED" | "FAILED" | "PENDING" | "EXPIRED" | "EXECUTION_BLOCKED" | "UNKNOWN" | "CANCELLED";
        };
        /** UserFact */
        UserFact: {
            /**
             * Authoritative Execution
             * @default false
             * @constant
             */
            authoritative_execution: false;
            /** Choice */
            choice: ("ACCEPT" | "DECLINE" | "DEFER") | null;
            /** Declaration */
            declaration: string | null;
            /** Event Id */
            event_id: string;
            /** Fact Id */
            fact_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "VIEWED" | "ACKNOWLEDGED" | "CONFIRMED" | "EXECUTION_DECLARED";
            /**
             * Reconciliation Status
             * @enum {string}
             */
            reconciliation_status: "NOT_APPLICABLE" | "PENDING";
            /** Recorded At */
            recorded_at: string;
            /** Report Version Id */
            report_version_id: string;
            /**
             * Synthetic
             * @default true
             * @constant
             */
            synthetic: true;
        };
        /** UserFactRequest */
        UserFactRequest: {
            /** Choice */
            choice?: ("ACCEPT" | "DECLINE" | "DEFER") | null;
            /** Declaration */
            declaration?: ("PREPARING" | "REPORTED_SUBMITTED" | "REPORTED_PARTIAL" | "REPORTED_FILLED" | "REPORTED_CANCELLED" | "UNABLE") | null;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "VIEWED" | "ACKNOWLEDGED" | "CONFIRMED" | "EXECUTION_DECLARED";
        };
        /**
         * VersionDiagnosticDto
         * @description Pydantic-only transport contract for the public diagnostic interface.
         */
        VersionDiagnosticDto: {
            /** Application Version */
            application_version: string;
            /** M Agent Release Commit */
            m_agent_release_commit: string;
            /** M Agent Version */
            m_agent_version: string;
            /** M Agent Wheel Sha256 */
            m_agent_wheel_sha256: string;
            /** M Agent Wheel Url */
            m_agent_wheel_url: string;
            /** Source Sha */
            source_sha: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authentication_options_api_v1_auth_passkeys_authentication_options_post: {
        parameters: {
            query?: never;
            header?: {
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDto"];
                };
            };
            /** @description No enrolled passkey is available */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    authentication_verify_api_v1_auth_passkeys_authentication_verify_post: {
        parameters: {
            query?: never;
            header?: {
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationVerificationDto"];
                };
            };
            /** @description Authentication verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    reauthentication_options_api_v1_auth_passkeys_reauthentication_options_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDto"];
                };
            };
            /** @description Recent authenticated session required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    reauthentication_verify_api_v1_auth_passkeys_reauthentication_verify_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReauthenticationVerificationDto"];
                };
            };
            /** @description Reauthentication verification failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    registration_options_api_v1_auth_passkeys_registration_options_post: {
        parameters: {
            query?: never;
            header: {
                "X-Host-Console-Grant": string;
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDto"];
                };
            };
            /** @description Host console grant required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    registration_verify_api_v1_auth_passkeys_registration_verify_post: {
        parameters: {
            query?: never;
            header?: {
                origin?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Registration verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    logout_api_v1_auth_session_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin, CSRF token, or session was invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    refresh_session_api_v1_auth_session_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRefreshDto"];
                };
            };
            /** @description Origin, CSRF token, or session was invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    safety_capabilities_diagnostic_api_v1_diagnostics_safety_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyCapabilitiesDiagnosticDto"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    version_diagnostic_api_v1_diagnostics_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDiagnosticDto"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    formal_report_api_v1_reports__report_version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_version_id: string;
            };
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormalReport"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Formal report not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    report_user_facts_api_v1_reports__report_version_id__facts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_version_id: string;
            };
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFact"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
    record_report_user_fact_api_v1_reports__report_version_id__facts_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                origin?: string | null;
            };
            path: {
                report_version_id: string;
            };
            cookie?: {
                "__Host-stock_profiler_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserFactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFact"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpaqueRequestErrorDto"];
                };
            };
        };
    };
}
